# Generated by Django 5.1.1 on 2024-09-18 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("bp_manager", "0002_remove_blueprint_likes_like"),
        ("bp_manager", "0003_alter_like_unique_together"),
    ]

    dependencies = [
        ("bp_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blueprint",
            name="likes",
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="bp_manager.blueprint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "blueprint")},
            },
        ),
    ]
